### ISSUE TITLE
Error while deploying application: the server could not find the requested resource

### ISSUE THREAD

**Issue by masteruser20** [kubernetes/kompose#1238]
Hello,

I'm trying to setup kubernetes services using docker-compose file and kompose app, and for test purposes Im using this repository:
[https://github.com/dockersamples/example-voting-app]( https://github.com/dockersamples/example-voting-app)

using this command:
` kompose up --verbose --push-image=false -f docker-compose.yml`

I have information that all the services were successfully created but there's fatal error occurred :

> FATA Error while deploying application: the server could not find the requested resource

kubectl versions:
Client Version: v1.17.1
Server Version: v1.17.1

kompose version:
1.20.0 (f3d54d784)

Also there is one more problem with image tag. As You can see docker-compose in this project contains some sections without image key and tag key which producing an error in building phase. I had to add some randomly names and tags for image. Is it intentional behavior or bug?

**Comment by hangyan** [comment]
1. I cannot reproduce this error. Can you try to use the `convert` command first to create all the yaml files and use `kubectl` to apply this files to find out which one cause the error?

2. The image tag should have been fixed by the master branch

**Comment by masteruser20** [comment]
All services has been created without problems, but deployment yml's and other throws errors:

> error: unable to recognize "db-deployment.yaml": no matches for kind "Deployment" in version "extensions/v1beta1"

> error: unable to recognize "front-tier-networkpolicy.yaml": no matches for kind "NetworkPolicy" in version "extensions/v1beta1"

**Comment by hangyan** [comment]
@masteruser20 This is a known issue, the fixed will be released in the next month. Sorry for your inconvenient

**Comment by vongohren** [comment]
@hangyan is there some sort of workaround on this? Im trying this sample: https://kompose.io/getting-started/ and I get the same error.
First I had to get past this issue: https://github.com/kubernetes/kompose/issues/1131
And then now hitting this.

This is the getting started guide, and it is not working out of the 📦 
What can I do to try to get it to work?

Using docker-compose on the file that it provides work. It converts into files aswell, but deploying the yaml files with kompose up, crashes with this error. Cannot find and more detailed errors

**Comment by hangyan** [comment]
This should be fixed in the next release. Use the master branch to build a local binary if you can

**Comment by febriyan1302** [comment]
> This should be fixed in the next release. Use the master branch to build a local binary if you can

okee i'm waiting your fixed release

**Comment by Yokutto** [comment]
@hangyan Cloning from master branch and building don't fix this problem:
>error: unable to recognize "front-tier-networkpolicy.yaml": no matches for kind "NetworkPolicy" in version "extensions/v1beta1"
But it's fixes
>error: unable to recognize "db-deployment.yaml": no matches for kind "Deployment" in version "extensions/v1beta1"

👍

**Comment by gsainsbury86** [comment]
> unable to recognize "internal-networkpolicy.yaml": no matches for kind "NetworkPolicy" in version "extensions/v1beta1"

I have the same problem with 1.21.0

**Comment by hangyan** [comment]
The `1.21` version fix the Deployment issue, but it clearly not enough. The network group will need some fix too.

**Comment by FaizHasan123** [comment]
@hangyan Are there any updates on the fix? I also ran into the same issue as @masteruser20. I am deploying the sample kompose app to an Openshift cluster running in IBM Cloud.

**Comment by hangyan** [comment]
I'm working on this fix now

**Comment by NicolasMilligan** [comment]
Any update on this? I'm running into the same problems as https://github.com/kubernetes/kompose/issues/1238#issue-552377250 and https://github.com/kubernetes/kompose/issues/1238#issuecomment-576555072 after using `kompose up` or `kompose convert && kubectl apply -f .`

**Comment by cummy2019** [comment]
Does anyone have any update on this? I am also getting same error

INFO Deploying application in "default" namespace 
INFO Successfully created Service: web            
FATA Error while deploying application: the server could not find the requested resource

**Comment by ecda909** [comment]
Same error?

**Comment by habtom-wmichael** [comment]
service/producteservice created
error: unable to recognize "deployment.yml": no matches for kind "Deployment" in version "extensions/v1beta1"

**Comment by asencis** [comment]
Are there any updates on this issue? 

```error: unable to recognize "kube.io/main-networkpolicy.yaml": no matches for kind "NetworkPolicy" in version "extensions/v1beta1"```

**Comment by hangyan** [comment]
@asencis Can you try the master build?

**Comment by mkbhanda** [comment]
No errors with compose version "1.22.0 (4b9b5066)" at least when providing the converted yaml to Kubectl. Much thanks @hangyan

**Comment by gowthamshashank** [comment]
error: unable to recognize "deployment.yml": no matches for kind "Deployment" in version "extensions/v1beta1"

**Comment by hangyan** [comment]
@gowthamshashank  This is fixed in the master branch

**Comment by ExperimentalHypothesis** [comment]
still getting this error unable to recognize "deployment.yml": no matches for kind "Deployment" in version "extensions/v1beta1"

**Comment by ExperimentalHypothesis** [comment]
still getting this error .. unable to recognize "deployment.yml": no matches for kind "Deployment" in version "extensions/v1beta1"

**Comment by hangyan** [comment]
@ExperimentalHypothesis Can you try the latest release?
